# Run the scbatch pipeline

This example runs the public pipeline on a small synthetic AnnData object. Scanpy owns filtering, neighbors, UMAP, and Leiden; scbatch owns the custom transformation and correction stages.

In [1]:
import os
import sys

import pandas as pd
from IPython.display import display
from pathlib import Path
from numpy import array

worktree_root = Path(
    "/Users/yishai/Desktop/build_pip_package/scbatch-basic-structure-creation"
).resolve()
if str(worktree_root) in sys.path:
    sys.path.remove(str(worktree_root))
sys.path.insert(0, str(worktree_root))

for module_name in tuple(sys.modules):
    if module_name == "scbatch" or module_name.startswith("scbatch."):
        sys.modules.pop(module_name)

import scbatch
from scbatch import run_pipeline

print(f"kernel_executable={sys.executable}")
print(f"working_directory={os.getcwd()}")
print(f"scbatch_path={scbatch.__file__}")
assert Path(scbatch.__file__).resolve().is_relative_to(worktree_root)

kernel_executable=/Users/yishai/Desktop/build_pip_package/scbatch/.venv/bin/python3
working_directory=/Users/yishai/Desktop/build_pip_package/scbatch-basic-structure-creation/examples
scbatch_path=/Users/yishai/Desktop/build_pip_package/scbatch-basic-structure-creation/scbatch/__init__.py

## Create pipeline input

The pipeline snapshots adata.X after every matrix-transforming stage. The default QC rule removes only empty profiles.

In [2]:
import numpy as np
from anndata import AnnData

X = np.arange(1, 121, dtype=float).reshape(30, 4)

adata = AnnData(X=X)
adata.obs["batch"] = ["reference"] * 15 + ["query"] * 15
adata.obs["is_anchor"] = [True] * 10 + [False] * 20
# adata.X

## Inspect a two-batch, six-sample AnnData object

multi_batch_adata.X is the measurement matrix: each row is one observation and each column is one marker. This example therefore has shape (60, 4): two batches, three samples per batch, ten observations per sample, and four markers. The object is separate from adata, so the pipeline example below remains unchanged.

## Load the supplied batches with scbatch

The loader infers every dimension from `dataset`, then uses `anchor_pairs` to label the paired anchor samples.

In [3]:
import sys
from pathlib import Path
import pandas as pd

worktree_root = Path(
    "/Users/yishai/Desktop/build_pip_package/scbatch-basic-structure-creation"
).resolve()
if str(worktree_root) in sys.path:
    sys.path.remove(str(worktree_root))
sys.path.insert(0, str(worktree_root))
for module_name in tuple(sys.modules):
    if module_name == "scbatch" or module_name.startswith("scbatch."):
        sys.modules.pop(module_name)

# Keep every summary column visible when the notebook renders a wide table.
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)
pd.set_option("display.max_colwidth", None)

from scbatch.datasets import load_demo, summarize_samples

synthetic_adata = load_demo("synthetic")
cytof_adata = load_demo("cytof")

# Use synthetic data for the extraction and pipeline cells below.
adata = synthetic_adata
synthetic_sample_summary = summarize_samples(synthetic_adata)
cytof_sample_summary = summarize_samples(cytof_adata)

print("Synthetic AnnData:")
print(synthetic_adata)
display(synthetic_sample_summary)

print("\nCYTOF AnnData:")
print(cytof_adata)
display(cytof_sample_summary)

Marker names:
['marker_1', 'marker_2', 'marker_3', 'marker_4']

Anchor pairs:
[{'from_batch': '0', 'from_sample': 0, 'to_batch': '1', 'to_sample': 0}, {'from_batch': '2', 'from_sample': 0, 'to_batch': '1', 'to_sample': 1}]

Marker names:
['marker_1', 'marker_2', 'marker_3', 'marker_4']

Anchor pairs:
[{'from_batch': '0', 'from_sample': 0, 'to_batch': '1', 'to_sample': 0}, {'from_batch': '2', 'from_sample': 0, 'to_batch': '1', 'to_sample': 1}]
Synthetic AnnData:
AnnData object with n_obs × n_vars = 150 × 4
    obs: 'batch', 'batch_index', 'sample', 'sample_index', 'sample_id', 'is_anchor', 'anchor_to_batch', 'anchor_to_batch_index', 'anchor_to_sample', 'anchor_to_sample_index'
    uns: 'anchor_pairs'

   batch  batch_index sample  sample_index         sample_id  is_anchor anchor_to_batch anchor_to_sample  sample_size
0      0            0      0             0  batch_0_sample_0       True               1                0           10
1      0            0      1             1  batch_0_sample_1      False   not_an_anchor    not_an_anchor           10
2      0            0      2             2  batch_0_sample_2      False   not_an_anchor    not_an_anchor           10
3      0            0      3             3  batch_0_sample_3      False   not_an_anchor    not_an_anchor           10
4      0            0      4             4  batch_0_sample_4      False   not_an_anchor    not_an_anchor           10
5      1            1      0             0  batch_1_sample_0       True               0                0           10
6      1            1      1             1  batch_1_sample_1       True               2                0           10
7      1            1      2             2  batch_1_sample_2      False   not_an_anchor    not_an_anchor           10
8      1            1      3             3  batch_1_sample_3      False   not_an_anchor    not_an_anchor           10
9      1            1      4             4  batch_1_sample_4      False   not_an_anchor    not_an_anchor           10
10     2            2      0             0  batch_2_sample_0       True               1                1           10
11     2            2      1             1  batch_2_sample_1      False   not_an_anchor    not_an_anchor           10
12     2            2      2             2  batch_2_sample_2      False   not_an_anchor    not_an_anchor           10
13     2            2      3             3  batch_2_sample_3      False   not_an_anchor    not_an_anchor           10
14     2            2      4             4  batch_2_sample_4      False   not_an_anchor    not_an_anchor           10

CYTOF AnnData:
AnnData object with n_obs × n_vars = 150 × 4
    obs: 'batch', 'batch_index', 'sample', 'sample_index', 'sample_id', 'is_anchor', 'anchor_to_batch', 'anchor_to_batch_index', 'anchor_to_sample', 'anchor_to_sample_index'
    uns: 'anchor_pairs'

   batch  batch_index sample  sample_index         sample_id  is_anchor anchor_to_batch anchor_to_sample  sample_size
0      0            0      0             0  batch_0_sample_0       True               1                0           10
1      0            0      1             1  batch_0_sample_1      False   not_an_anchor    not_an_anchor           10
2      0            0      2             2  batch_0_sample_2      False   not_an_anchor    not_an_anchor           10
3      0            0      3             3  batch_0_sample_3      False   not_an_anchor    not_an_anchor           10
4      0            0      4             4  batch_0_sample_4      False   not_an_anchor    not_an_anchor           10
5      1            1      0             0  batch_1_sample_0       True               0                0           10
6      1            1      1             1  batch_1_sample_1       True               2                0           10
7      1            1      2             2  batch_1_sample_2      False   not_an_anchor    not_an_anchor           10
8      1            1      3             3  batch_1_sample_3      False   not_an_anchor    not_an_anchor           10
9      1            1      4             4  batch_1_sample_4      False   not_an_anchor    not_an_anchor           10
10     2            2      0             0  batch_2_sample_0       True               1                1           10
11     2            2      1             1  batch_2_sample_1      False   not_an_anchor    not_an_anchor           10
12     2            2      2             2  batch_2_sample_2      False   not_an_anchor    not_an_anchor           10
13     2            2      3             3  batch_2_sample_3      False   not_an_anchor    not_an_anchor           10
14     2            2      4             4  batch_2_sample_4      False   not_an_anchor    not_an_anchor           10

## Extract individual samples

`iter_samples` yields each original sample as an `n × m` NumPy array, followed by its input batch index and sample index.

In [3]:
import sys
from pathlib import Path
import pandas as pd

worktree_root = Path(
    "/Users/yishai/Desktop/build_pip_package/scbatch-basic-structure-creation"
).resolve()
if str(worktree_root) in sys.path:
    sys.path.remove(str(worktree_root))
sys.path.insert(0, str(worktree_root))
for module_name in tuple(sys.modules):
    if module_name == "scbatch" or module_name.startswith("scbatch."):
        sys.modules.pop(module_name)


from scbatch.datasets import load_demo, summarize_samples
from scbatch.pp import filter_cells


# Keep every summary column visible when the notebook renders a wide table.
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)
pd.set_option("display.max_colwidth", None)


adata = load_demo("synthetic")
adata_summary = summarize_samples(adata)
print(adata)
display(adata_summary)


filter_cells(adata, min_counts=1)
print(f"Observations after sample-wise filtering: {adata.n_obs}")

Marker names:
['marker_1', 'marker_2', 'marker_3', 'marker_4']

Anchor pairs:
[{'from_batch': '0', 'from_sample': 0, 'to_batch': '1', 'to_sample': 0}, {'from_batch': '2', 'from_sample': 0, 'to_batch': '1', 'to_sample': 1}]
AnnData object with n_obs × n_vars = 150 × 4
    obs: 'batch', 'batch_index', 'sample', 'sample_index', 'sample_id', 'is_anchor', 'anchor_to_batch', 'anchor_to_batch_index', 'anchor_to_sample', 'anchor_to_sample_index'
    uns: 'anchor_pairs'

   batch  batch_index sample  sample_index         sample_id  is_anchor anchor_to_batch anchor_to_sample  sample_size
0      0            0      0             0  batch_0_sample_0       True               1                0           10
1      0            0      1             1  batch_0_sample_1      False   not_an_anchor    not_an_anchor           10
2      0            0      2             2  batch_0_sample_2      False   not_an_anchor    not_an_anchor           10
3      0            0      3             3  batch_0_sample_3      False   not_an_anchor    not_an_anchor           10
4      0            0      4             4  batch_0_sample_4      False   not_an_anchor    not_an_anchor           10
5      1            1      0             0  batch_1_sample_0       True               0                0           10
6      1            1      1             1  batch_1_sample_1       True               2                0           10
7      1            1      2             2  batch_1_sample_2      False   not_an_anchor    not_an_anchor           10
8      1            1      3             3  batch_1_sample_3      False   not_an_anchor    not_an_anchor           10
9      1            1      4             4  batch_1_sample_4      False   not_an_anchor    not_an_anchor           10
10     2            2      0             0  batch_2_sample_0       True               1                1           10
11     2            2      1             1  batch_2_sample_1      False   not_an_anchor    not_an_anchor           10
12     2            2      2             2  batch_2_sample_2      False   not_an_anchor    not_an_anchor           10
13     2            2      3             3  batch_2_sample_3      False   not_an_anchor    not_an_anchor           10
14     2            2      4             4  batch_2_sample_4      False   not_an_anchor    not_an_anchor           10

Observations after sample-wise filtering: 147

## Run the scbatch pipeline

ArcSinh, QQ correction, and core normalization currently use a temporary adata.X + 1 operation. This notebook demonstrates orchestration and representation storage, not validated batch-correction science.

In [5]:
pipeline_result = run_pipeline(
    adata,
    method="qq",
    clustering_is_leiden=True,
)
print(pipeline_result.layers)
expected_layers = {
    "Gated",
    "arcsinh",
    "batch_corrected",
    "core_normalized",
    "scaled",
    "umap",
    "leiden",
}
assert expected_layers <= set(pipeline_result.layers)
assert "X_umap" in pipeline_result.obsm
assert "leiden" in pipeline_result.obs
pipeline_result

Layers with keys: Gated, arcsinh, batch_corrected, core_normalized, scaled, umap, leiden

AnnData object with n_obs × n_vars = 147 × 4
    obs: 'batch', 'batch_index', 'sample', 'sample_index', 'sample_id', 'is_anchor', 'anchor_to_batch', 'anchor_to_batch_index', 'anchor_to_sample', 'anchor_to_sample_index', 'n_counts', 'leiden'
    var: 'mean', 'std'
    uns: 'anchor_pairs', 'neighbors', 'umap', 'leiden'
    obsm: 'X_umap'
    layers: 'Gated', 'arcsinh', 'batch_corrected', 'core_normalized', 'scaled', 'umap', 'leiden'
    obsp: 'distances', 'connectivities'